<?php
session_start();
if (!isset($_SESSION["user_id"])) { header("Location: login.php"); exit; }
if (($_SESSION["role"] ?? "technician") !== "admin") { http_response_code(403); exit("Access denied. Administrator access is required."); }
require_once __DIR__ . "/../config/database.php";
$pdo->exec("CREATE TABLE IF NOT EXISTS gauge_equipment_settings (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, equipment_name VARCHAR(255) NOT NULL DEFAULT '', equipment_range VARCHAR(255) NOT NULL DEFAULT '', equipment_serial VARCHAR(255) NOT NULL DEFAULT '', equipment_calibration_date DATE NULL, equipment_due_date DATE NULL, equipment_qty VARCHAR(100) NOT NULL DEFAULT '', equipment_certification_no VARCHAR(255) NOT NULL DEFAULT '', updated_by INT UNSIGNED NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$pdo->exec("INSERT INTO gauge_equipment_settings (id,equipment_name,equipment_range) VALUES (1,'DEADWEIGHT TESTER','20-10000 PSI') ON DUPLICATE KEY UPDATE id=id");
$msg=$err="";
if($_SERVER["REQUEST_METHOD"]==='POST'){ $s=$pdo->prepare("UPDATE gauge_equipment_settings SET equipment_name=?,equipment_range=?,equipment_serial=?,equipment_calibration_date=?,equipment_due_date=?,equipment_qty=?,equipment_certification_no=?,updated_by=? WHERE id=1"); $s->execute([trim($_POST['equipment_name']??''),trim($_POST['equipment_range']??''),trim($_POST['equipment_serial']??''),($_POST['equipment_calibration_date']??'')?:null,($_POST['equipment_due_date']??'')?:null,trim($_POST['equipment_qty']??''),trim($_POST['equipment_certification_no']??''),(int)$_SESSION['user_id']]); $msg='GAUGE CALIBRATION EQUIPMENT UPDATED SUCCESSFULLY.'; }
$r=$pdo->query("SELECT * FROM gauge_equipment_settings WHERE id=1")->fetch(PDO::FETCH_ASSOC) ?: [];
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gauge Equipment Settings</title><style>body{font-family:Arial;background:#f4f4f4;margin:0;color:#111}.wrap{max-width:800px;margin:30px auto;padding:20px}.card{background:#fff;padding:25px;border-top:5px solid #c00;box-shadow:0 4px 15px #0001}.tag{background:#111;color:#fff;padding:8px;font-size:11px}.field{margin:15px 0}.field label{display:block;font-weight:bold;font-size:11px;margin-bottom:6px}.field input{width:100%;padding:12px;box-sizing:border-box;border:1px solid #ccc}.btn{background:#c00;color:#fff;border:0;padding:13px 18px;font-weight:bold}.ok{background:#e8f8ee;color:#075b28;padding:12px;margin-bottom:15px}</style></head><body><main class="wrap"><a href="dashboard.php">← Dashboard</a><h1>Gauge Equipment Settings</h1><p>Only administrators can update the calibration equipment used on new Gauge certificates.</p><?php if($msg):?><div class="ok">✓ <?=htmlspecialchars($msg)?></div><?php endif;?><section class="card"><span class="tag">GAUGE CALIBRATION EQUIPMENT</span><form method="post"><div class="field"><label>Equipment Name</label><input name="equipment_name" value="<?=htmlspecialchars($r['equipment_name']??'')?>" required></div><div class="field"><label>Equipment Range</label><input name="equipment_range" value="<?=htmlspecialchars($r['equipment_range']??'')?>" required></div><div class="field"><label>Serial No.</label><input name="equipment_serial" value="<?=htmlspecialchars($r['equipment_serial']??'')?>"></div><div class="field"><label>Calibration Date</label><input type="date" name="equipment_calibration_date" value="<?=htmlspecialchars($r['equipment_calibration_date']??'')?>"></div><div class="field"><label>Next Due Date</label><input type="date" name="equipment_due_date" value="<?=htmlspecialchars($r['equipment_due_date']??'')?>"></div><div class="field"><label>Quantity</label><input name="equipment_qty" value="<?=htmlspecialchars($r['equipment_qty']??'')?>"></div><div class="field"><label>Certificate No.</label><input name="equipment_certification_no" value="<?=htmlspecialchars($r['equipment_certification_no']??'')?>"></div><button class="btn">SAVE GAUGE EQUIPMENT</button></form></section></main></body></html>