<?php
session_start();
if (!isset($_SESSION["user_id"])) { header("Location: ../auth/login.php"); exit; }
if ($_SERVER["REQUEST_METHOD"] !== "POST") { header("Location: valve.php"); exit; }
require_once __DIR__ . "/../config/database.php";
function postv($n,$d=''){return isset($_POST[$n])&&!is_array($_POST[$n])?trim((string)$_POST[$n]):$d;}
function uploadImage($field,$prefix){if(!isset($_FILES[$field])||$_FILES[$field]['error']===UPLOAD_ERR_NO_FILE)return null;$f=$_FILES[$field];if($f['error']!==UPLOAD_ERR_OK||$f['size']<=0||$f['size']>2*1024*1024)throw new RuntimeException('Invalid upload for '.$prefix.'.');$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);$allowed=['image/png'=>'png','image/jpeg'=>'jpg','image/webp'=>'webp'];if(!isset($allowed[$mime])||@getimagesize($f['tmp_name'])===false)throw new RuntimeException($prefix.' must be a PNG, JPG or WebP image.');$dir=__DIR__.'/uploads/'.($prefix==='stamp'?'stamps':'signatures');if(!is_dir($dir)&&!mkdir($dir,0755,true))throw new RuntimeException('Unable to create upload directory.');$name=$prefix.'_'.bin2hex(random_bytes(12)).'.'.$allowed[$mime];if(!move_uploaded_file($f['tmp_name'],$dir.'/'.$name))throw new RuntimeException('Unable to save upload.');return 'uploads/'.($prefix==='stamp'?'stamps':'signatures').'/'.$name;}
try{
$pdo->exec("CREATE TABLE IF NOT EXISTS valve_certificates (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, certificate_no VARCHAR(100) NOT NULL UNIQUE, client VARCHAR(255) NOT NULL, nuprc VARCHAR(255) NULL, test_location VARCHAR(255) NULL, tested_item VARCHAR(255) NULL, valve_class VARCHAR(255) NULL, serial_no VARCHAR(255) NULL, matp VARCHAR(255) NULL, test_date DATE NULL, body_test_date DATE NULL, seat_test_date DATE NULL, body_total_time VARCHAR(100) NULL, seat_total_time VARCHAR(100) NULL, body_medium VARCHAR(100) NULL, seat_medium VARCHAR(100) NULL, body_final_pressure VARCHAR(100) NULL, seat_final_pressure VARCHAR(100) NULL, tested_by VARCHAR(255) NULL, tested_name VARCHAR(255) NULL, witnessed_by VARCHAR(255) NULL, tested_signature VARCHAR(255) NULL, witnessed_signature VARCHAR(255) NULL, stamp_image VARCHAR(255) NULL, created_by INT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$pdo->exec("CREATE TABLE IF NOT EXISTS valve_pressure_log (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, valve_id INT UNSIGNED NOT NULL, description VARCHAR(255) NOT NULL, cavity_body_test VARCHAR(255) NULL, seat_test VARCHAR(255) NULL, remarks VARCHAR(255) NULL, sort_order INT NOT NULL DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX(valve_id), CONSTRAINT fk_valve_pressure_log_valve FOREIGN KEY(valve_id) REFERENCES valve_certificates(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$pdo->exec("CREATE TABLE IF NOT EXISTS valve_physical_checks (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, valve_id INT UNSIGNED NOT NULL, check_left VARCHAR(255) NULL, result_left VARCHAR(100) NULL, check_right VARCHAR(255) NULL, result_right VARCHAR(100) NULL, sort_order INT NOT NULL DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX(valve_id), CONSTRAINT fk_valve_physical_valve FOREIGN KEY(valve_id) REFERENCES valve_certificates(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$pdo->exec("CREATE TABLE IF NOT EXISTS nuprc_settings (id INT UNSIGNED PRIMARY KEY, nuprc VARCHAR(255) NOT NULL DEFAULT '', updated_by INT UNSIGNED NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");$pdo->exec("INSERT INTO nuprc_settings (id,nuprc) VALUES (1,'') ON DUPLICATE KEY UPDATE id=id");$nuprc=(string)($pdo->query("SELECT nuprc FROM nuprc_settings WHERE id=1")->fetchColumn()?:'');
$no=postv('certificate_no');$client=postv('client');if($no==='')throw new RuntimeException('Certificate number is required.');if($client==='')throw new RuntimeException('Client is required.');
$dups=$pdo->prepare("SELECT id FROM valve_certificates WHERE certificate_no=:n LIMIT 1");$dups->execute([':n'=>$no]);if($dups->fetchColumn()!==false)throw new RuntimeException('CERTIFICATE NUMBER ALREADY USED: '.$no);
foreach([['gauge_calibrations','Gauge'],['recorder_calibrations','Recorder']] as $pair){try{$exists=$pdo->query("SHOW TABLES LIKE '{$pair[0]}'")->fetchColumn();if($exists){$q=$pdo->prepare("SELECT id FROM {$pair[0]} WHERE certificate_no=:n LIMIT 1");$q->execute([':n'=>$no]);if($q->fetchColumn()!==false)throw new RuntimeException('CERTIFICATE NUMBER ALREADY USED BY '.$pair[1].': '.$no);}}catch(PDOException $ignore){}}
$testedSig=uploadImage('tested_signature','tested');$witnessedSig=uploadImage('witnessed_signature','witnessed');$stamp=uploadImage('stamp_image','stamp');
$stmt=$pdo->prepare("INSERT INTO valve_certificates (certificate_no,client,nuprc,test_location,tested_item,valve_class,serial_no,matp,test_date,body_test_date,seat_test_date,body_total_time,seat_total_time,body_medium,seat_medium,body_final_pressure,seat_final_pressure,tested_by,tested_name,witnessed_by,tested_signature,witnessed_signature,stamp_image,created_by) VALUES (:no,:client,:nuprc,:loc,:item,:class,:serial,:matp,:td,:bd,:sd,:btime,:stime,:bm,:sm,:bfp,:sfp,:tb,:tn,:wb,:ts,:ws,:stamp,:uid)");$stmt->execute([':no'=>$no,':client'=>$client,':nuprc'=>$nuprc,':loc'=>postv('test_location'),':item'=>postv('tested_item'),':class'=>postv('valve_class'),':serial'=>postv('serial_no'),':matp'=>postv('matp'),':td'=>postv('test_date')?:null,':bd'=>postv('body_test_date')?:null,':sd'=>postv('seat_test_date')?:null,':btime'=>postv('body_total_time'),':stime'=>postv('seat_total_time'),':bm'=>postv('body_medium'),':sm'=>postv('seat_medium'),':bfp'=>postv('body_final_pressure'),':sfp'=>postv('seat_final_pressure'),':tb'=>postv('tested_by'),':tn'=>postv('tested_name'),':wb'=>postv('witnessed_by'),':ts'=>$testedSig,':ws'=>$witnessedSig,':stamp'=>$stamp,':uid'=>(int)$_SESSION['user_id']]);$id=(int)$pdo->lastInsertId();
$descs=$_POST['description']??[];$bodies=$_POST['body_log']??[];$seats=$_POST['seat_log']??[];$remarks=$_POST['remarks']??[];$ins=$pdo->prepare("INSERT INTO valve_pressure_log (valve_id,description,cavity_body_test,seat_test,remarks,sort_order) VALUES (:vid,:d,:b,:s,:r,:o)");foreach($descs as $i=>$d){$d=trim((string)$d);if($d==='')continue;$ins->execute([':vid'=>$id,':d'=>$d,':b'=>trim((string)($bodies[$i]??'')),':s'=>trim((string)($seats[$i]??'')),':r'=>trim((string)($remarks[$i]??'')),':o'=>$i]);}
$cl=$_POST['check_left']??[];$rl=$_POST['result_left']??[];$cr=$_POST['check_right']??[];$rr=$_POST['result_right']??[];$pin=$pdo->prepare("INSERT INTO valve_physical_checks (valve_id,check_left,result_left,check_right,result_right,sort_order) VALUES (:v,:cl,:rl,:cr,:rr,:o)");foreach($cl as $i=>$v){$pin->execute([':v'=>$id,':cl'=>trim((string)$v),':rl'=>trim((string)($rl[$i]??'')),':cr'=>trim((string)($cr[$i]??'')),':rr'=>trim((string)($rr[$i]??'')),':o'=>$i]);}
header('Location: valve-certificate.php?id='.$id);exit;
}catch(Throwable $e){http_response_code(400);$msg=htmlspecialchars($e->getMessage(),ENT_QUOTES,'UTF-8');echo "<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'><title>CMS | Valve Save Error</title><style>body{font-family:Arial;background:#f4f5f7;margin:0;min-height:100vh;display:grid;place-items:center}.box{background:#fff;padding:30px;max-width:600px;border-radius:12px;box-shadow:0 12px 40px #0001;text-align:center}h1{color:#b40000}a{display:inline-block;margin-top:18px;background:#111;color:#fff;padding:12px 18px;text-decoration:none}</style></head><body><div class='box'><h1>VALVE CERTIFICATE NOT SAVED</h1><p>{$msg}</p><a href='valve.php'>BACK TO VALVE CERTIFICATE</a></div></body></html>";}
